[package]
name = "ttt"
version = "0.1.0"
edition = "2021"
authors = "C0las"
description = "A 2 player tic tac toe game."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
